import Head from 'next/head'
import Hero from '../components/Hero'
import ContactMe from '../components/ContactMe'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import { useParallax, ParallaxProvider } from 'react-scroll-parallax'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ParallaxProvider>
          <Hero />
          <Skills />
          <Projects />
        </ParallaxProvider>
      </main>
    </div>
  )
}
