import Head from 'next/head'
import Hero from '../components/Hero'
import Feedbacks from '../components/Feedbacks'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import { ParallaxProvider } from 'react-scroll-parallax'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Salim.D</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ParallaxProvider>
          <Hero />
          <Skills />
          <Projects />
          <Feedbacks />
        </ParallaxProvider>
      </main>
    </div>
  )
}
